### ISSUE TITLE
Add 2 address

### ISSUE THREAD

**Issue by petroDavydov** [SlenkyDev/StopRussia.net.ua#14]
Hello.
I cloned your repo and try to add 2 address? but I can't add branch, so,  can you add 2 address? like this

"http://www.fsb.ru/ ": {
        number_of_requests: 0,
        number_of_errored_responses: 0,
	},
	"https://www.tinkoff.ru/ ": {
        number_of_requests: 0,
        number_of_errored_responses: 0,
	},
	
	With respect, Petro

**Comment by SlenkyDev** [comment]
Hi there,
I will review the sites provided and add them, if necessary,

I can see that you're from Ukraine as well, I just want to wish you good luck in the war, let's hope this all ends soon.

Slenky

**Comment by petroDavydov** [comment]
Hi, thank you
