### ISSUE TITLE
Add variable in address to each resource

### ISSUE THREAD

**Issue by greenycat** [SlenkyDev/StopRussia.net.ua#19]
domain.com?rand_val_name=rand_value

This will make caching on targets less useful

**Comment by xHyroM** [comment]
> domain.com?rand_val_name=rand_value
> 
> This will make caching on targets less useful

I'll do pr

**Comment by stuchl4n3k** [comment]
Note that targets support an optional `pattern` attribute which can probably solve your use case like this:

`pattern: 'https://domain.ru?%STR=%NUM'`

**Comment by SlenkyDev** [comment]
Hi there, mind putting it in a pr?

------- Original Message -------
