### ISSUE TITLE
No data transferred

### ISSUE THREAD

**Issue by rottenstonks** [SlenkyDev/StopRussia.net.ua#2]
Few thousand requests sent out, 0 bytes transferred.
Another thing is, each request has "[stoprussia.net.ua](http://stoprussia.net.ua/)" as a referer, so they can be trivially flagged and blocked.

Thoughts? @SlenkyDev.

**Comment by SlenkyDev** [comment]
> Few thousand requests sent out, 0 bytes transferred. Another thing is, each request has "[stoprussia.net.ua](http://stoprussia.net.ua/)" as a referer, so they can be trivially flagged and blocked.
> 
> Thoughts? @SlenkyDev.

Yes, most of the sites (if not all) are down currently, that's why data might no be getting transferred.
I'll take a look at what I can do about the referer, thanks!

**Comment by SlenkyDev** [comment]
Fixed? https://github.com/SlenkyDev/StopRussia.net.ua/commit/c3f9d065491ed41dd16873022b1b1e40b4168c4a

**Comment by moritzebeling** [comment]
I also get the classic CORS error but this is prbly a problem with the whole approach. I mean the target server _is_ occupied by issuing the CORS error, but this prbly only has a low impact...

**Comment by SlenkyDev** [comment]
> I also get the classic CORS error but this is prbly a problem with the whole approach. I mean the target server _is_ occupied by issuing the CORS error, but this prbly only has a low impact...

You'd be correct with that one. It does make a small impact, but it still does something even with CORS enabled.

It's best to go into the Chrome installation folder and manually run the browser using
`chrome.exe --disable-web-security --disable-gpu --user-data-dir="D:/chrome"`
You may have to use a different "user data dir". This will start a clean instance with none of your data and the security policies disabled, you will be hitting all of the websites that are online.
