### ISSUE TITLE
Satisfy new requests from other pseudo-information websites to join the global shut down

### ISSUE THREAD

**Issue by fabri86** [SlenkyDev/StopRussia.net.ua#3]
Good morning,
not enough privileges for me to push and open a PR.

Would you mind to consider new join requests?

Presentational:

`"https://yandex.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
                "error_message": "Failed to fetch"
            },
            "https://sputniknews.com/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
                "error_message": "Failed to fetch"
            },
            "https://inosmi.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
                "error_message": "Failed to fetch"
            },
            "https://gazeta.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
                "error_message": "Failed to fetch"
            },
            "https://kommersant.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
                "error_message": "Failed to fetch"
            },
            "https://rubaltic.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
                "error_message": "Failed to fetch"
            },
            "https://ura.news/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
                "error_message": "Failed to fetch"
            },`

new items: 
            
            `"https://yandex.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
            },
            "https://sputniknews.com/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
            },
            "https://inosmi.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
            },
            "https://gazeta.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
            },
            "https://kommersant.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
            },
            "https://rubaltic.ru/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
            },
            "https://ura.news/": {
                number_of_requests: 0,
                number_of_errored_responses: 0,
            },`

**Comment by SlenkyDev** [comment]
I'm pretty sure you can submit PRs, but you need to have the repository forked.

**Comment by SlenkyDev** [comment]
Can I close?

**Comment by fabri86** [comment]
Absolutely!!
