### ISSUE TITLE
What about brining this to an epic level

### ISSUE THREAD

**Issue by fabri86** [SlenkyDev/StopRussia.net.ua#4]
What about using any vectors of cyber and DDoS attacks on these resources?

Copy pasting the idea from some of my colleagues:

Task # 1 We encourage you to use any vectors of cyber and DDoS attacks on these resources. 

Business corporations:

Gazprom - https://www.gazprom.ru/ 
Lukoil - https://lukoil.ru 
Magnet - https://magnit.ru/ 
Norilsk Nickel - https://www.nornickel.com/ 
Surgetneftegas - https://www.surgutneftegas.ru/ 
Tatneft - https://www.tatneft.ru/ 
Evraz - https://www.evraz.com/ru/ 
NLMK - https://nlmk.com/ 
Sibur Holing - https://www.sibur.ru/ 
Severstal - https://www.severstal.com/ 
Metalloinvest - https://www.metalloinvest.com/ 
NNC - https://nangs.org/ 
Russian Copper Company - https://rmk-group.ru/ru/ 
TMK - https://www.tmk-group.ru/ 
Yandex - https://ya.ru/ 
Polymetal International - https://www.polymetalinternational.com/ru/ 
Uralkali - https://www.uralkali.com/ru/ 
Eurosibenergo - https://www.eurosib.ru/ 
OMK - https://omk.ru/ 

Banks 
Sberbank - https://www.sberbank.ru 
VTB - https://www.vtb.ru/ 
Gazprombank - https://www.gazprombank.ru/ 
Sovcombank - https://sovcombank.ru/
Novikom - https://novikom.ru/

The state

Public services - https://www.gosuslugi.ru/ 
Moscow State Services - https://www.mos.ru/uslugi/ 
President of the Russian Federation - http://kremlin.ru/ 
Government of the Russian Federation - http://government.ru/ 
Ministry of Defense - https://mil.ru/ 
Tax - https://www.nalog.gov.ru/ 
Customs - https://customs.gov.ru/ 
Pension Fund - https://pfr.gov.ru/ 
Roskomnadzor - https://rkn.gov.ru/

**Comment by rottenstonks** [comment]
@SlenkyDev Just FYI, source for those links suggested above comes from here: https://t.me/itarmyofukraine2022/5

**Comment by SlenkyDev** [comment]
Yes, thank you!
I will take a look at the sites and see what I can do.

**Comment by rottenstonks** [comment]
Found these in an external Private Bin link, for what it is worth. Thanks for adding many more links to the page; it is appreciated.

https://notes.anonpaste.org/?1bb604798b2004c2#Go4Zf3mDnkv62JVfbtXAdYi4yi6B8t5NDL77uC4kFEJR
